SEARCH_RESULTS_COUNT = 3
SEARCH_RELEVANT_RESULTS = 10
MIN_SEARCH_LENGTH = 2

PAGE_TREE_ENABLED = True
PAGE_TREE_ALL_VISIBLE = True

PAGE_TREE_TITLE = "Sitemap" # The title of the page tree view
# Snippet Generation Configuration
SNIPPET_PRE_LENGTH = 150
SNIPPET_POST_LENGTH = 150
